project:
  type: website
  output-dir: docs

website:
  title: "Gus Lipkin's Awesome Website"
  navbar:
    background: primary
    left:
      - href: about.qmd
        text: About Me
      - href: talks.qmd
        text: My Talks
      # - href: resume.qmd
      #   text: Résumé
      - text: My Blogs
        menu:
          - href: professional-blog.qmd
            text: My Professional Blog
          - href: personal-blog.qmd
            text: My Personal Blog
      - href: contact.qmd
        text: Contact Me
    tools:
      - href: https://www.linkedin.com/in/guslipkin/
        icon: linkedin
      - href: https://www.github.com/guslipkin
        icon: github
      - href: https://guslipkin.medium.com/
        icon: medium
      - href: https://fosstodon.org/@guslipkin
        icon: mastodon
      - href: https://www.instagram.com/guslipkin
        icon: instagram

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto
  cache: true


