---
title: "My Résumé"
site-path: "/resume"

$enable-grid-classes: false
$enable-cssgrid: true
---

<style>
	#center { width: 70%; }
	.noBorder { border:none !important; }
	.container { display: flex; }
	.column { flex: 1; }

	.flex-container {
    display: flex;
    flex-wrap: wrap;
  }

  .flex-item {
    flex: 25%;
  }

	.grid-container {
		display: grid;
		grid-template-columns: 1fr 2fr 1fr;
	}
	.item-1 {
		grid-column:  1; 
		grid-row:  1;
		}
	.item-2 {
		grid-column: 2;
		grid-row: 1;
	}
	.item-3 {
		grid-column: 3;
		grid-row: 1;
		text-align: right;
	}

	.grid-job {
		display: grid;
		grid-template-columns: 3fr 1fr;
	}
	.job {
		grid-column: 1;
		grid-row:  1;
		color: #e91d63;
		text-indent: -1.5em; 
		padding-left: 1.5em;
	}
	.time {
		grid-column: 2;
		grid-row: 1;
		text-align: right;
		color:  #666666;
		font-size: 12px;
	}

	@media (max-width: 700px) {
		.flex-item {
    		flex: 33.33%;
  		}

		.grid-container {
			display: grid;
			justify-items: center;
		}
		.item-1 {
			grid-column:  2; 
			grid-row:  2;
		}
		.item-2 {
			grid-column: 2;
			grid-row: 1;
		}
		.item-3 {
			grid-column: 2;
			grid-row: 3;
			text-align: center;
		}

		.grid-job {
			display: grid;
			grid-template-columns: 1fr;
		}
		.job {
			grid-column: 1;
			grid-row:  1;
			color: #e91d63;
			text-indent: -1.5em; 
			padding-left: 1.5em;
		}
		.time {
			grid-column: 1;
			grid-row: 2;
			text-align: left;
			color:  #666666;
			font-size: 12px;
		}
	}

	/* style from: https://codepen.io/mlms13/pen/LKFoy */
	.letter {
  	background: #fff;
  	box-shadow: 0 0 10px rgba(0,0,0,0.3);
  	margin: 26px auto 0;
  	max-width: auto;
  	min-height: 300px;
  	padding: 24px;
  	padding-left: 4.5%;
  	padding-right: 4.5%;
  	position: relative;
	}
	.letter:before, .letter:after {
  	content: "";
  	height: 98%;
  	position: absolute;
  	width: 100%;
  	z-index: -1;
	}
	.letter:before {
  	background: #fafafa;
  	box-shadow: 0 0 8px rgba(0,0,0,0.2);
  	left: -5px;
  	top: 4px;
  	--width:  10vw;
  	transform: rotate(-2.5deg);
	}
	.letter:after {
  	background: #f6f6f6;
  	box-shadow: 0 0 3px rgba(0,0,0,0.2);
  	right: -3px;
  	top: 1px;
  	transform: rotate(1.4deg);
	}
	/* end attribution */
</style>

### [🖨 Print a copy](assets/Gus_Lipkin_Resume_for_GitHub.pdf) {.unnumbered .unlisted}

<div class="letter resumeClass" id="resume">

<div style="color:#e91d63; font-size: 42px; text-align: center;">
<b>Gus Lipkin</b>
</div>
----
<h3 style="margin-bottom: 0px; color:#404040;">What Drives Me</h3>
<div>
<p style="font-size: 14px; color:#666666; padding-left: 20px; padding-right: 20px; text-align: justify; text-justify: auto;">
I’ve always loved asking ‘how?’ and ‘why?’ Since starting my journey as a data scientist, I’ve been able to answer ‘how?’ by developing tools to support my teammates and clients, while answering ‘why?’ with analyses to support data driven decision making. I’m looking for a position where I can develop my career using my skills to make a positive impact both within the company and with external clients and business partners.
</p>
</div>

<h3 style="margin-bottom: 0px; color:#404040;">Experience</h3>
<div class="grid-job">
<div class="job">
<span><b>Data Scientist</b></span>
<span style="color:#2e4440"><em> – Lander Analytics</em></span>
</div>
<div class="time">Jul 2023 - Present</div>
</div>
<ul style="font-size: 14px; color:#666666;">
  <li>Meet with clients from project start through completion, discussing key metrics and progress at every step</li>
  <li>Complete code reviews and make suggestions for clients and instruct them on data science best practices</li>
  <li>Build data pipelines in <b>R</b> or <b>Python</b> using tools such as <b>Kestra</b>, <b>Prefect</b>, and <b>targets</b> for orchestration</li>
  <li>Create interactive content using <b>Quarto</b> with <b>Observable JS</b> and <b>DuckDB</b> or <b>Shiny for R</b> hosted in <b>Docker</b></li>
  <li>Maintain a working knowledge of <b>Unix and <b>Linux</b> systems to help diagnose and resolve issues with data science infrastructure including the <b>Posit Workbench</b>, <b>Connect</b>, and <b>Package Manager</b></li>
  <li>Directly contribute to open source R packages such as <b>renv</b> and <b>blastula</b> while sparking discussions in others</li>
</ul>

<div class="grid-job">
<div class="job">
<span><b>Data Analyst</b></span>
<span style="color:#2e4440"><em> – Publix Super Markets</em></span>
</div>
<div class="time">May 2022 - May 2023</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Develop novel analyses and models to provide key insights to business stakeholders including store managers</li>
	<li>Build and maintain internal R packages to aid in analysis such as ‘publixdate’ for working with Publix’s system of dates or ‘pubsub’ for general utilities and a streamlined database connection interface</li>
	<li>Seek out and participate in strategic initiatives which require analytic support from across corporate</li>
  <li>Visualize data and create reports in <b>Power BI</b> to display model performance and facilitate data-driven decisions</li>
</ul>

<div class="grid-job">
<div class="job">
<span><b>Data Science Project Team Lead</b></span>
<span style="color:#2e4440"><em> – Tallahassee Memorial Healthcare</em></span>
</div>
<div class="time">Aug 2021 - May 2022</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Correlate patient feedback to readmissions and patient experience using <b>linear regression</b> and <b>decision trees</b></li>
	<li>Create an interactive training tool for nurses using results found in the analysis with <b>HTML</b> and <b>JavaScript</b></li>
	<li>Work with capstone sponsor to define project timeline and goals and author a report on project findings</li>
</ul>

<h3 style="margin-bottom: 0px; color:#404040;">Projects</h3>
<div class="grid-job">
<div class="job">
<span><b>AEDify</b></span>
<span style="color:#2e4440"><em> – Lander Analytics</em></span>
</div>
<div class="time">Jul 2024 - Present</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Develop AEDify, a custom occupancy forecasting tool leveraging <b>AI</b> and machine learning technologies to help inform building operations decisions allowing for significant operational adjustments turned cost savings</li>
	<li>Meet with development partners to hear feedback and improve user interface and user experience</li>
</ul>
<div class="grid-job">
<div class="job">
<span><b>Interactive Dashboard with Observable JS and DuckDB</b></span>
<span style="color:#2e4440"><em> – Lander Analytics</em></span>
</div>
<div class="time">Jul 2024 - Present</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Worked to replace a client’s Shiny for R dashboard with ObservableJS and DuckDB to reduce hosting costs</li>
	<li>Defined project goals and milestones and met with the client biweekly to ensure the project met expectations</li>
	<li>Delivered the project on time and successfully transferred domain knowledge to the client team</li>
</ul>
<div class="grid-job">
<div class="job">
<span><b>Shrink Narrative Reports</b></span>
<span style="color:#2e4440"><em> – Publix Super Markets</em></span>
</div>
<div class="time">May 2022 - Aug 2022</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Built a fully automated reporting pipeline with R and <b>Python</b> in for <b>Spark</b> in a <b>Databricks</b> environment that delivers monthly PDF reports to all Publix stores to support goals to reduce retail shrink</li>
	<li>Analyzes store shrink metrics and provides actionable insights through targeted operations suggestions</li>
	<li>Built and implemented a <b>SQL</b> translation function leveraging the <b>tidyverse</b>, <b>dbplyr</b>, and <b>sparklyr</b> to expedite writing new targeted operations suggestions as operations leaders see demand</li>
	<li>Completed the project four months ahead of schedule and saved $85k per year in contracting costs</li>
</ul>
<div class="grid-job">
<div class="job">
<span><b>Store/Item Activation Recommendations</b></span>
<span style="color:#2e4440"><em> – Publix Super Markets</em></span>
</div>
<div class="time">April 2023 - May 2023</div>
</div>
<ul style="font-size: 14px; color:#666666;">
	<li>Implemented a <b>machine learning</b> recommendation system to optimize store/item availability combinations</li>
	<li>Accepts any combination of stores and items and imputes data for missing combinations</li>
	<li>Uses the <b>tidymodels</b> suite to cluster stores based on similar latent features from the recommendation process</li>
	<li>Pioneered “project as a package” for easier documentation, maintenance, legibility, requirements, and usability</li>
</ul>

<h3 style="margin-bottom: 0px; color:#404040;">Education</h3>

<div class="grid-job">
<div class="job"><b>Florida Polytechnic University</b></div>
<div class="time">Aug 2018 - May 2022</div>
</div>
<div style="text-indent: -1.5em; padding-left: 1.5em;">
<span style="color:#2e4440; padding-left: 1.5em;"><em>– Bachelor of Science, Business Analytics with concentrations in Quantitative Economics & Econometrics and Intelligent Mobility</em></span>
<br>
<span style="color:#2e4440;"><em>– Associate of Arts</em></span>
</div>

</div>
